name: forge
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - xarray=2025.6.1
  - dask=2025.5.1
  - netcdf4=1.7.2
  - numba=0.61.2
  - windspharm=2.0.0
  - pyyaml=6.0.2
  - h5netcdf
  - h5py
  - zarr>=2,<3
  - numcodecs
  - cftime
  - pytest
